language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: SBYPw4dBw8S9T8b7S53afASqUfq/eSr7yHo9pFbjW7ux3hj32dJZqIck+XYFPjIdqlp4o39myh/AY304KGgtVjkxZ7npx+3cy89IodPKjaGmIUKtkp4z2qrRQk9nyAdCSHVdVAJBL78YyxST8hR/0FQMuh2qHTQHgWteiDW5cXN2Bv0wXzrEkUJk6bMhhJZ09cpBubltI/KW4c5Uwl4Uwgl1OihizxtrLrVd0/wcPQ23JvCQM6Z5Dq2lvY7+mu0hQYXdp0tFlSlMnYkiaat/dkjjzpNviEyZJCgLAU8HKg1FFFEKUZkjqxATchphprJastPV/Zgz9GeF+lqfFwRH0FLSpaIdE8g88oObffRmCN6w5noOxklfH1MiB4pLiS82ztUXPs4S+xDPpo31ceWgEViXXQcsbToXaUbk2ymTUc/Il4Ym/DtvCo+xnOiulUuoB7AE4PoulD+/po0wZDuVFJeD3CoPi/ypbPRFzhpns7zAVNTXtp8unJu7G+dN6X4J/4tZRcpmgCi+goS7/fbqL40kydXTLQVGX/Jv/g30vpvy+22iuH6Jcqk+GkOtzWKonG19Wlbt8ViCHttJ6sd0Vs6gHVFW47wH/xgfrYqCW1hyiuuekUGtTv4JrP3O3r4yJQrTON7LsPQk8sstKr6vHwB+zL/W6qZChpO8OzjX3xs=
