# Site settings
title: Daniel C. LaCombe, Jr
email: daniel.lacombe.jr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Dan's personal website for  sharing and discussing scientific topics through words and code. Come join the discussion.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dlacombejr.github.io" # the base hostname & protocol for your site
twitter_username: daniellacombejr
github_username:  dlacombejr

# Build settings
markdown: kramdown

...
layout: default
comments: twitter_username
...
