# Site settings
title: Daniel C. LaCombe, Jr
email: dlacombejr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a website for disseminating scientific information and for open discourse with the community at large. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dlacombejr.github.io" # the base hostname & protocol for your site
twitter_username: daniellacombejr
github_username:  dlacombejr

# Build settings
markdown: kramdown
